// <auto-generated />
namespace EFfluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class OrderConfiguration : IEntityTypeConfiguration<Order>
{
    public void Configure(EntityTypeBuilder<Order> builder)
    {
        builder.ToTable("Orders", "dbo");
		builder.HasKey(e => e.Id);
		builder.Ignore(e => e.TemporaryToken);
		builder.HasOne(x => x.User).WithMany(x => x.Orders).HasForeignKey(x => x.UserId).IsRequired();

        builder.Property(x => x.Name).IsRequired().HasMaxLength(50);
        builder.Property(x => x.Description).IsUnicode(true).HasMinLength(10);
        builder.Property(x => x.price).HasPrecision(18, 2);
        builder.Property(x => x.ProductUrl);
        builder.Property(x => x.email);
		builder.Property(x => x.CustomColumn).HasColumnName("MyColumn").HasColumnType("varchar(50)");
		builder.Property(x => x.CustomColumnNameOnly).HasColumnName("CustomColumnNameOnly");
		builder.Property(x => x.RowVersion).IsRowVersion().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate();

    }
}
