// <auto-generated />
namespace EFfluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class ProfileConfiguration : IEntityTypeConfiguration<Profile>
{
    public void Configure(EntityTypeBuilder<Profile> builder)
    {
		builder.ToTable("Profiles", "dbo");
		builder.HasNoKey();
		builder.HasComment("Main Profile table");
		builder.HasIndex(e => e.Email);
		builder.Ignore(e => e.Tags);
		builder.HasOne(x => x.User).WithOne(x => x.Profile).HasForeignKey<Profile>(x => x.UserId).IsRequired();

        builder.Property(x => x.Name);
		builder.Property(x => x.Email);
    }
}
