// <auto-generated />
namespace EFFluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
		builder.ToTable("Users", "dbo");
		builder.HasIndex(e => e.Email).IsUnique().HasDatabaseName("IX_User_Email");

		builder.Ignore(e => e.TemporaryToken);
		builder.Ignore(e => e.TemporaryToken2);
		builder.HasOne(x => x.Manager).WithMany(x => x.Subordinates).HasForeignKey(x => x.ManagerId);

        builder.Property(x => x.Id).ValueGeneratedOnAdd();
        builder.Property(x => x.Name).IsRequired().HasMaxLength(50);
		        builder.Property(x => x.Email).IsRequired(false);
		builder.Property(x => x.FirstName).HasMaxLength(50);
		builder.Property(x => x.RowGuid).IsConcurrencyToken();

    }
}
