// <auto-generated />
namespace EFFluentify.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class ContactConfiguration : IEntityTypeConfiguration<Contact>
{
    public void Configure(EntityTypeBuilder<Contact> builder)
    {
        builder.HasIndex(e => e.Email).IsUnique().HasDatabaseName("IX_Contact_Email");
        builder.HasIndex(e => new { e.LastName, e.FirstName });
        builder.Property(x => x.Id);
        builder.Property(x => x.Email).HasMaxLength(320);
        builder.Property(x => x.FirstName);
        builder.Property(x => x.LastName);
        builder.Property(x => x.CountryCode).IsUnicode(false);
        builder.Property(x => x.Bio).IsUnicode();
        builder.Property(x => x.Priority);
    }
}