// <auto-generated />
namespace EFfluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("User");

        builder.Property(x => x.Id);
    }
}

internal sealed class PostConfiguration : IEntityTypeConfiguration<Post>
{
    public void Configure(EntityTypeBuilder<Post> builder)
    {
        builder.HasOne(x => x.Author).WithMany().HasForeignKey(x => x.UserId).IsRequired();
        builder.HasOne(x => x.Editor).WithMany().HasForeignKey(x => x.EditorId).IsRequired();

        builder.Property(x => x.Id);
    }
}

internal sealed class RoleConfiguration : IEntityTypeConfiguration<Role>
{
    public void Configure(EntityTypeBuilder<Role> builder)
    {
        builder.ToTable("Role");

        builder.Property(x => x.Id);
    }
}

internal sealed class AdminConfiguration : IEntityTypeConfiguration<Admin>
{
    public void Configure(EntityTypeBuilder<Admin> builder)
    {
        builder.HasOne(x => x.Role).WithMany().HasForeignKey(x => x.RoleId).IsRequired();

        builder.Property(x => x.Id);
    }
}

internal sealed class CompositeConfiguration : IEntityTypeConfiguration<Composite>
{
    public void Configure(EntityTypeBuilder<Composite> builder)
    {
        builder.ToTable("Composite");

        builder.Property(x => x.Key1);
        builder.Property(x => x.Key2);
    }
}

internal sealed class CompositeChildConfiguration : IEntityTypeConfiguration<CompositeChild>
{
    public void Configure(EntityTypeBuilder<CompositeChild> builder)
    {
        builder.HasOne(x => x.Composite).WithMany().HasForeignKey(x => new { x.CKey1, x.CKey2 }).IsRequired();

        builder.Property(x => x.Id);
    }
}

internal sealed class CategoryConfiguration : IEntityTypeConfiguration<Category>
{
    public void Configure(EntityTypeBuilder<Category> builder)
    {
        builder.HasOne(x => x.Parent).WithMany(x => x.Children).HasForeignKey(x => x.ParentId);

        builder.Property(x => x.Id);
    }
}

internal sealed class BlogConfiguration : IEntityTypeConfiguration<Blog>
{
    public void Configure(EntityTypeBuilder<Blog> builder)
    {
        builder.ToTable("Blog");

        builder.Property(x => x.Id);
    }
}

internal sealed class BlogDetailConfiguration : IEntityTypeConfiguration<BlogDetail>
{
    public void Configure(EntityTypeBuilder<BlogDetail> builder)
    {
        builder.HasKey(e => e.BlogId);
        builder.HasOne(x => x.Blog).WithOne(x => x.Detail).HasForeignKey<BlogDetail>(x => x.BlogId).IsRequired();

    }
}

internal sealed class OrderConfiguration : IEntityTypeConfiguration<Order>
{
    public void Configure(EntityTypeBuilder<Order> builder)
    {
        builder.HasOne(x => x.OptionalCustomer).WithMany(x => x.OptionalOrders).HasForeignKey(x => x.OptionalCustomerId);
        builder.HasOne(x => x.RequiredCustomer).WithMany(x => x.RequiredOrders).HasForeignKey(x => x.RequiredCustomerId).IsRequired();

        builder.Property(x => x.Id);
    }
}

internal sealed class CustomerConfiguration : IEntityTypeConfiguration<Customer>
{
    public void Configure(EntityTypeBuilder<Customer> builder)
    {
        builder.ToTable("Customer");

        builder.Property(x => x.Id);
    }
}

