using System.Text;
using EFfluentify.Domain.Helpers;
using EFfluentify.Application.Interfaces;
using EFfluentify.Domain.Models;
using EFfluentify.Domain.Rules.Interfaces;
using EFfluentify.Application.Models;

namespace EFfluentify.Infrastructure.CodeGen
{
    public sealed class CSharpConfigEmitter : ICodeGenerator
    {
        private IRuleRegistry _rules;
        private IReadOnlyList<EntityModel> _entities = [];

        public CSharpConfigEmitter()
        {
            _entities = [];
            _rules = default!;
        }

        public Dictionary<string, string> Generate(IEnumerable<EntityModel> entities, PipelineOptions options, IRuleRegistry rules)
        {
            _rules = rules ?? throw new ArgumentNullException(nameof(rules));
            _entities = entities?.ToList() ?? throw new ArgumentNullException(nameof(entities));

            return options.ManyFiles 
                ? GenerateMultipleFiles(options.RootNamespace) 
                : GenerateSingleFile(options.RootNamespace);
        }

        private Dictionary<string, string> GenerateMultipleFiles(string rootNs)
        {
            var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            
            foreach (var e in _entities)
            {
                var sb = AddHeader(rootNs);
                AppendConfig(sb, e);
                map[$"{e.Name}Configuration.cs"] = sb.ToString();
            }

            return map;
        }

        private Dictionary<string, string> GenerateSingleFile(string rootNs)
        {
            var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var sb = AddHeader(rootNs);
            
            foreach (var e in _entities)
            {
                AppendConfig(sb, e);
                sb.AppendLine();
            }
            
            map["EntityConfigurations.cs"] = sb.ToString();
            return map;
        }

        private void AppendConfig(StringBuilder sb, EntityModel entity)
        {
            sb.AppendLine($"internal sealed class {entity.Name}Configuration : IEntityTypeConfiguration<{entity.Name}>");
            sb.AppendLine("{");
            sb.AppendLine($"    public void Configure(EntityTypeBuilder<{entity.Name}> builder)");
            sb.AppendLine("    {");

            var entityLines = GenerateEntityConfiguration(entity);
            if (entityLines.Count > 0)
            {
                foreach (var line in entityLines)
                    sb.AppendLine($"        {line}");
                sb.AppendLine();
            }

            sb.AppendLine();

            ConfigureProperties(sb, entity);

            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        private List<string> GenerateEntityConfiguration(EntityModel entity)
        {
            return _rules.GetCallsForEntity(entity).ToList();
        }

        private void ConfigureProperties(StringBuilder sb, EntityModel entity)
        {
            var metadata = new EntityMetadata(entity, _entities);

            foreach (var prop in entity.Properties)
            {
                if (metadata.IsNavigationProperty(prop) || metadata.IsIgnored(prop.Name))
                {
                    continue;
                }

                var propertyLines = _rules.GetCallsForProperty(prop)
                                          .Where(line => !string.IsNullOrWhiteSpace(line))
                                          .ToList();

                if (ShouldSkipProperty(prop.Name, propertyLines.Count, metadata))
                {
                    continue;
                }

                sb.Append($"        builder.Property(x => x.{prop.Name})");

                foreach (var line in propertyLines.Distinct(StringComparer.Ordinal))
                {
                    sb.Append(line);
                }

                sb.AppendLine(";");
            }
        }

        private static bool ShouldSkipProperty(string propName, int lineCount, EntityMetadata metadata)
        {
            if (lineCount > 0)
                return false;

            return metadata.IsKey(propName) || metadata.IsForeignKey(propName);
        }

        private static StringBuilder AddHeader(string rootNs)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"namespace {rootNs};");
            sb.AppendLine();
            sb.AppendLine("using Microsoft.EntityFrameworkCore;");
            sb.AppendLine("using Microsoft.EntityFrameworkCore.Metadata.Builders;");
            sb.AppendLine();
            return sb;
        }

        private sealed class EntityMetadata
        {
            private readonly IReadOnlyList<EntityModel> _allEntities;
            private readonly HashSet<string> _keyProperties;
            private readonly HashSet<string> _ignoredProperties;
            private readonly HashSet<string> _foreignKeyProperties;

            public EntityMetadata(EntityModel entity, IReadOnlyList<EntityModel> allEntities)
            {
                _allEntities = allEntities;
                _keyProperties = GetKeyProperties(entity);
                _ignoredProperties = GetIgnoredProperties(entity);
                _foreignKeyProperties = GetForeignKeyProperties(entity);
            }

            public bool IsNavigationProperty(Property prop) => EfTypeHelper.IsNavigationProperty(prop, _allEntities);
            public bool IsIgnored(string propName) => _ignoredProperties.Contains(propName);
            public bool IsKey(string propName) => _keyProperties.Contains(propName);
            public bool IsForeignKey(string propName) => _foreignKeyProperties.Contains(propName);

            private static HashSet<string> GetKeyProperties(EntityModel entity)
            {
                return entity.Properties
                    .Where(EfTypeHelper.HasKeyAttribute)
                    .Select(p => p.Name)
                    .ToHashSet(StringComparer.OrdinalIgnoreCase);
            }

            private static HashSet<string> GetIgnoredProperties(EntityModel entity)
            {
                return entity.Properties
                    .Where(EfTypeHelper.HasNotMappedAttribute)
                    .Select(p => p.Name)
                    .ToHashSet(StringComparer.OrdinalIgnoreCase);
            }

            private HashSet<string> GetForeignKeyProperties(EntityModel entity)
            {
                var fkPropNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

                foreach (var prop in entity.Properties)
                {
                    var fkAttr = EfTypeHelper.TryGetForeignKeyAttribute(prop);
                    if (fkAttr == null)
                        continue;

                    var arg0 = fkAttr.PositionalArgs.FirstOrDefault();
                    if (string.IsNullOrWhiteSpace(arg0))
                        continue;

                    if (EfTypeHelper.IsNavigationProperty(prop, _allEntities) || EfTypeHelper.IsCollectionType(prop.TypeName))
                    {
                        foreach (var fk in EfTypeHelper.SplitFkNames(arg0))
                            fkPropNames.Add(fk);
                    }
                    else
                    {
                        fkPropNames.Add(prop.Name);
                    }
                }
                return fkPropNames;
            }
        }
    }
}
