// <auto-generated />
namespace EFfluentify.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class BlogConfiguration : IEntityTypeConfiguration<Blog>
{
    public void Configure(EntityTypeBuilder<Blog> builder)
    {
        builder.Property(x => x.Id);
    }
}

internal sealed class PostConfiguration : IEntityTypeConfiguration<Post>
{
    public void Configure(EntityTypeBuilder<Post> builder)
    {
        builder.HasOne(x => x.Blog).WithMany(x => x.Posts).HasForeignKey(x => x.BlogId).IsRequired();
        builder.Property(x => x.Id);
    }
}

internal sealed class AuthorConfiguration : IEntityTypeConfiguration<Author>
{
    public void Configure(EntityTypeBuilder<Author> builder)
    {
        builder.Property(x => x.Id);
    }
}

internal sealed class BookConfiguration : IEntityTypeConfiguration<Book>
{
    public void Configure(EntityTypeBuilder<Book> builder)
    {
        builder.HasOne(x => x.AuthorNav).WithMany(x => x.Books).HasForeignKey(x => x.AuthorId).IsRequired();
        builder.Property(x => x.Id);
    }
}

internal sealed class TeamConfiguration : IEntityTypeConfiguration<Team>
{
    public void Configure(EntityTypeBuilder<Team> builder)
    {
        builder.HasKey(e => new { e.TeamId, e.LeagueId });
    }
}

internal sealed class PlayerConfiguration : IEntityTypeConfiguration<Player>
{
    public void Configure(EntityTypeBuilder<Player> builder)
    {
        builder.HasOne(x => x.Team).WithMany(x => x.Players).HasForeignKey(x => new { x.MyTeamId, x.MyLeagueId }).IsRequired();
        builder.Property(x => x.Id);
    }
}

internal sealed class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
{
    public void Configure(EntityTypeBuilder<Employee> builder)
    {
        builder.HasOne(x => x.Manager).WithMany(x => x.Subordinates).HasForeignKey(x => x.ManagerId);
        builder.Property(x => x.Id);
    }
}

internal sealed class CarConfiguration : IEntityTypeConfiguration<Car>
{
    public void Configure(EntityTypeBuilder<Car> builder)
    {
        builder.Property(x => x.Id);
    }
}

internal sealed class EngineConfiguration : IEntityTypeConfiguration<Engine>
{
    public void Configure(EntityTypeBuilder<Engine> builder)
    {
        builder.HasOne(x => x.Car).WithOne(x => x.Engine).HasForeignKey<Engine>(x => x.CarId).IsRequired();
        builder.Property(x => x.Id);
    }
}

internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.Property(x => x.Id);
    }
}

internal sealed class UserProfileConfiguration : IEntityTypeConfiguration<UserProfile>
{
    public void Configure(EntityTypeBuilder<UserProfile> builder)
    {
        builder.HasKey(e => e.Id);
        builder.HasOne(x => x.User).WithOne(x => x.Profile).HasForeignKey<UserProfile>(x => x.Id).IsRequired();
    }
}

internal sealed class CourseConfiguration : IEntityTypeConfiguration<Course>
{
    public void Configure(EntityTypeBuilder<Course> builder)
    {
        builder.HasOne(x => x.Teacher).WithMany().HasForeignKey(x => x.TeacherId);
        builder.HasOne(x => x.Department).WithMany().HasForeignKey(x => x.DepartmentId).IsRequired();
        builder.Property(x => x.Id);
    }
}

internal sealed class TeacherConfiguration : IEntityTypeConfiguration<Teacher>
{
    public void Configure(EntityTypeBuilder<Teacher> builder)
    {
        builder.Property(x => x.Id);
    }
}

internal sealed class DepartmentConfiguration : IEntityTypeConfiguration<Department>
{
    public void Configure(EntityTypeBuilder<Department> builder)
    {
        builder.Property(x => x.Id);
    }
}

internal sealed class ParentConfiguration : IEntityTypeConfiguration<Parent>
{
    public void Configure(EntityTypeBuilder<Parent> builder)
    {
        builder.Property(x => x.Id);
    }
}

internal sealed class ChildConfiguration : IEntityTypeConfiguration<Child>
{
    public void Configure(EntityTypeBuilder<Child> builder)
    {
        builder.HasOne(x => x.Mother).WithMany(x => x.ChildrenByMother).HasForeignKey(x => x.MotherId).IsRequired().OnDelete(DeleteBehavior.NoAction);
        builder.HasOne(x => x.Father).WithMany(x => x.ChildrenByFather).HasForeignKey(x => x.FatherId).IsRequired().OnDelete(DeleteBehavior.NoAction);
        builder.Property(x => x.Id);
    }
}

internal sealed class FlightConfiguration : IEntityTypeConfiguration<Flight>
{
    public void Configure(EntityTypeBuilder<Flight> builder)
    {
        builder.HasOne(x => x.DepartureAirport).WithMany(x => x.DepartingFlights).HasForeignKey(x => x.DepartureAirportId).IsRequired().OnDelete(DeleteBehavior.Restrict);
        builder.HasOne(x => x.ArrivalAirport).WithMany(x => x.ArrivingFlights).HasForeignKey(x => x.ArrivalAirportId).IsRequired();
        builder.Property(x => x.Id);
    }
}

internal sealed class AirportConfiguration : IEntityTypeConfiguration<Airport>
{
    public void Configure(EntityTypeBuilder<Airport> builder)
    {
        builder.Property(x => x.Id);
    }
}

internal sealed class VendorConfiguration : IEntityTypeConfiguration<Vendor>
{
    public void Configure(EntityTypeBuilder<Vendor> builder)
    {
        builder.Property(x => x.Id);
    }
}

internal sealed class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.HasOne(x => x.Vendor).WithMany(x => x.Products).HasForeignKey(x => x.VendorIdentifier).IsRequired();
        builder.Property(x => x.Id);
    }
}