// <auto-generated />
namespace EFFluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class BookConfiguration : IEntityTypeConfiguration<Book>
{
    public void Configure(EntityTypeBuilder<Book> builder)
    {
        builder.HasOne(x => x.AuthorNav).WithMany(x => x.Books).HasForeignKey(x => x.AuthorId).IsRequired();

        builder.Property(x => x.Id);
    }
}
