// <auto-generated />
namespace EFfluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class ChildConfiguration : IEntityTypeConfiguration<Child>
{
    public void Configure(EntityTypeBuilder<Child> builder)
    {
        builder.HasOne(x => x.Mother).WithMany(x => x.ChildrenByMother).HasForeignKey(x => x.MotherId).IsRequired().OnDelete(DeleteBehavior.NoAction);
        builder.HasOne(x => x.Father).WithMany(x => x.ChildrenByFather).HasForeignKey(x => x.FatherId).IsRequired().OnDelete(DeleteBehavior.NoAction);

        builder.Property(x => x.Id);
    }
}
