// <auto-generated />
namespace EFfluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class CourseConfiguration : IEntityTypeConfiguration<Course>
{
    public void Configure(EntityTypeBuilder<Course> builder)
    {
        builder.HasOne(x => x.Teacher).WithMany().HasForeignKey(x => x.TeacherId);
        builder.HasOne(x => x.Department).WithMany().HasForeignKey(x => x.DepartmentId).IsRequired();

        builder.Property(x => x.Id);
    }
}
