// <auto-generated />
namespace EFFluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class EngineConfiguration : IEntityTypeConfiguration<Engine>
{
    public void Configure(EntityTypeBuilder<Engine> builder)
    {
        builder.HasOne(x => x.Car).WithOne(x => x.Engine).HasForeignKey<Engine>(x => x.CarId).IsRequired();

        builder.Property(x => x.Id);
    }
}
