// <auto-generated />
namespace EFfluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class FlightConfiguration : IEntityTypeConfiguration<Flight>
{
    public void Configure(EntityTypeBuilder<Flight> builder)
    {
        builder.HasOne(x => x.DepartureAirport).WithMany(x => x.DepartingFlights).HasForeignKey(x => x.DepartureAirportId).IsRequired().OnDelete(DeleteBehavior.Restrict);
        builder.HasOne(x => x.ArrivalAirport).WithMany(x => x.ArrivingFlights).HasForeignKey(x => x.ArrivalAirportId).IsRequired();

        builder.Property(x => x.Id);
    }
}
