// <auto-generated />
namespace EFfluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class PlayerConfiguration : IEntityTypeConfiguration<Player>
{
    public void Configure(EntityTypeBuilder<Player> builder)
    {
        builder.HasOne(x => x.Team).WithMany(x => x.Players).HasForeignKey(x => new { x.MyTeamId, x.MyLeagueId }).IsRequired();

        builder.Property(x => x.Id);
    }
}
