// <auto-generated />
namespace EFFluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class PostConfiguration : IEntityTypeConfiguration<Post>
{
    public void Configure(EntityTypeBuilder<Post> builder)
    {
        builder.HasOne(x => x.Blog).WithMany(x => x.Posts).HasForeignKey(x => x.BlogId).IsRequired();

        builder.Property(x => x.Id);
    }
}
