// <auto-generated />
namespace EFFluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.HasOne(x => x.Vendor).WithMany(x => x.Products).HasForeignKey(x => x.VendorIdentifier).IsRequired();

        builder.Property(x => x.Id);
    }
}
