// <auto-generated />
namespace EFfluentify.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class OrderConfiguration : IEntityTypeConfiguration<Order>
{
    public void Configure(EntityTypeBuilder<Order> builder)
    {
        builder.ToTable("Orders", "dbo");
		builder.HasKey(e => e.Id);
		builder.Ignore(e => e.TemporaryToken);
		builder.HasOne(x => x.User).WithMany(x => x.Orders).HasForeignKey(x => x.UserId).IsRequired();

        builder.Property(x => x.Name).IsRequired().HasMaxLength(50);
        builder.Property(x => x.Description).IsUnicode(true);
        builder.Property(x => x.price).HasPrecision(18, 2);
        builder.Property(x => x.ProductUrl);
        builder.Property(x => x.email);
		builder.Property(x => x.CustomColumn).HasColumnName("MyColumn").HasColumnType("varchar(50)");
		builder.Property(x => x.CustomColumnNameOnly).HasColumnName("CustomColumnNameOnly");
		builder.Property(x => x.RowVersion).IsRowVersion().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate();

    }
}

internal sealed class ProfileConfiguration : IEntityTypeConfiguration<Profile>
{
    public void Configure(EntityTypeBuilder<Profile> builder)
    {
		builder.ToTable("Profiles", "dbo");
		builder.HasNoKey();
		builder.HasComment("Main Profile table");
		builder.HasIndex(e => e.Email);
		builder.Ignore(e => e.Tags);
		builder.HasOne(x => x.User).WithOne(x => x.Profile).HasForeignKey<Profile>(x => x.UserId).IsRequired();

        builder.Property(x => x.Name);
		builder.Property(x => x.Email);
    }
}

internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
		builder.ToTable("Users", "dbo");
		builder.HasIndex(e => e.Email).IsUnique().HasDatabaseName("IX_User_Email");

		builder.Ignore(e => e.TemporaryToken);
		builder.Ignore(e => e.TemporaryToken2);
		builder.HasOne(x => x.Manager).WithMany(x => x.Subordinates).HasForeignKey(x => x.ManagerId);

        builder.Property(x => x.Id).ValueGeneratedOnAdd();
        builder.Property(x => x.Name).IsRequired().HasMaxLength(50);
		        builder.Property(x => x.Email).IsRequired(false);
		builder.Property(x => x.FirstName).HasMaxLength(50);
		builder.Property(x => x.RowGuid).IsConcurrencyToken();


    }
}
