// <auto-generated />
namespace EFFluentify.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class ExchangeRateConfiguration : IEntityTypeConfiguration<ExchangeRate>
{
    public void Configure(EntityTypeBuilder<ExchangeRate> builder)
    {
        builder.HasIndex(e => new { e.Currency, e.Year }).IsUnique().HasDatabaseName("IX_ExchangeRate_Currency_Year");
        builder.HasKey(e => new { e.Currency, e.Year });
        builder.Property(x => x.Rate).HasPrecision(18, 6);
    }
}