<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>effluentify</ToolCommandName>
    <PackageId>EFFluentify.Tool</PackageId>
    <Version>1.0.1</Version>
    <Authors>Hosam Eldeen Reda</Authors>
    <Description>A .NET CLI tool that converts Entity Framework Core Data Annotations into equivalent Fluent API IEntityTypeConfiguration&lt;T&gt; classes, using Roslyn.</Description>
    <PackageTags>efcore;entity-framework;fluent-api;data-annotations;roslyn;dotnet-tool;codegen</PackageTags>
    <PackageProjectUrl>https://github.com/hosamr/EfFluentify</PackageProjectUrl>
    <RepositoryUrl>https://github.com/hosamr/EfFluentify</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="System.CommandLine" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFFluentify.Application\EFFluentify.Application.csproj" />
    <ProjectReference Include="..\EFFluentify.Domain\EFFluentify.Domain.csproj" />
    <ProjectReference Include="..\EFFluentify.Infrastructure\EFFluentify.Infrastructure.csproj" />
  </ItemGroup>

</Project>
