using EFFluentify.Application.Models;
using EFFluentify.Domain.Models;
using EFFluentify.Domain.Rules;
using EFFluentify.Infrastructure.CodeGen;
using Xunit;
using static EFFluentify.Tests.Helpers.ModelFactory;

namespace EFFluentify.Tests.Unit.CodeGen
{
    [Trait("Category", "Unit")]
    public class CSharpConfigEmitterTests
    {
        private static readonly RuleRegistryFactory Factory = new();

        private static Dictionary<string, string> Generate(IReadOnlyList<EntityModel> entities, PipelineOptions options)
        {
            var rules = Factory.Create(entities);
            return new CSharpConfigEmitter().Generate(entities, options, rules);
        }

        [Fact]
        public void ManyFiles_ProducesOneFilePerEntity()
        {
            var entities = new[]
            {
                Entity("User", new[] { Prop("Id", "int") }),
                Entity("Order", new[] { Prop("Id", "int") })
            };

            var files = Generate(entities, new PipelineOptions { ManyFiles = true });

            Assert.Equal(2, files.Count);
            Assert.True(files.ContainsKey("UserConfiguration.cs"));
            Assert.True(files.ContainsKey("OrderConfiguration.cs"));
        }

        [Fact]
        public void SingleFile_ProducesOneCombinedFile()
        {
            var entities = new[]
            {
                Entity("User", new[] { Prop("Id", "int") }),
                Entity("Order", new[] { Prop("Id", "int") })
            };

            var files = Generate(entities, new PipelineOptions { ManyFiles = false });

            Assert.Single(files);
            Assert.True(files.ContainsKey("EntityConfigurations.cs"));
            var content = files["EntityConfigurations.cs"];
            Assert.Contains("class UserConfiguration", content);
            Assert.Contains("class OrderConfiguration", content);
        }

        [Fact]
        public void EmitsHeader_ClassDeclaration_And_PropertyCalls()
        {
            var entities = new[]
            {
                Entity("User", new[]
                {
                    Prop("Id", "int"),
                    Prop("Name", "string", nullable: false, attrs: new[] { Attr("Required") })
                })
            };

            var content = Generate(entities, new PipelineOptions { ManyFiles = true, RootNamespace = "My.Configs" })["UserConfiguration.cs"];

            Assert.Contains("// <auto-generated />", content);
            Assert.Contains("namespace My.Configs;", content);
            Assert.Contains("internal sealed class UserConfiguration : IEntityTypeConfiguration<User>", content);
            Assert.Contains("builder.Property(x => x.Id);", content);
            Assert.Contains("builder.Property(x => x.Name).IsRequired();", content);
        }

        [Fact]
        public void SkipsNavigationProperties()
        {
            var entities = new[]
            {
                Entity("Post", new[]
                {
                    Prop("Id", "int"),
                    Prop("Blog", "Blog") // navigation to another entity
                }),
                Entity("Blog", new[] { Prop("Id", "int") })
            };

            var content = Generate(entities, new PipelineOptions { ManyFiles = true })["PostConfiguration.cs"];

            Assert.DoesNotContain("builder.Property(x => x.Blog)", content);
        }

        [Fact]
        public void SkipsNotMappedProperties()
        {
            var entities = new[]
            {
                Entity("User", new[]
                {
                    Prop("Id", "int"),
                    Prop("Temp", "string", attrs: new[] { Attr("NotMapped") })
                })
            };

            var content = Generate(entities, new PipelineOptions { ManyFiles = true })["UserConfiguration.cs"];

            Assert.DoesNotContain("builder.Property(x => x.Temp)", content);
            Assert.Contains("builder.Ignore(e => e.Temp);", content);
        }

        [Fact]
        public void SkipsBareKeyProperty_ButEmitsHasKey()
        {
            var entities = new[]
            {
                Entity("Thing", new[] { Prop("Id", "int", attrs: new[] { Attr("Key") }) })
            };

            var content = Generate(entities, new PipelineOptions { ManyFiles = true })["ThingConfiguration.cs"];

            Assert.Contains("builder.HasKey(e => e.Id);", content);
            Assert.DoesNotContain("builder.Property(x => x.Id)", content);
        }

        [Fact]
        public void Generate_NullEntities_Throws()
        {
            Assert.Throws<ArgumentNullException>(() =>
                new CSharpConfigEmitter().Generate(null!, new PipelineOptions(), Factory.Create()));
        }

        [Fact]
        public void Generate_NullRules_Throws()
        {
            Assert.Throws<ArgumentNullException>(() =>
                new CSharpConfigEmitter().Generate(new[] { Entity("X") }, new PipelineOptions(), null!));
        }

        [Fact]
        public void Generate_WithInvalidEntityName_ReturnsUnformattedSourceGracefully()
        {
            // An entity name that is not a valid C# identifier produces code with syntax errors;
            // the emitter should fall back to returning the raw (unformatted) source rather than throw.
            var entities = new[] { Entity("1Bad", new[] { Prop("Id", "int") }) };

            var content = Assert.Single(Generate(entities, new PipelineOptions { ManyFiles = true })).Value;

            Assert.Contains("1BadConfiguration", content);
        }
    }
}
