<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Redpoint.ThirdParty.System.CommandLine" Version="2025.1276.372" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFfluentify.Domain\EFfluentify.Domain.csproj" />
  </ItemGroup>

</Project>
