<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ExpectedOutputRemoval\**" />
    <EmbeddedResource Remove="ExpectedOutputRemoval\**" />
    <None Remove="ExpectedOutputRemoval\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="TestData\Order.cs" />
    <Compile Remove="TestData\TestCase1\Order.cs" />
    <Compile Remove="TestData\TestCase1\Profile.cs" />
    <Compile Remove="TestData\TestCase1\User.cs" />
    <Compile Remove="TestData\TestFkCases\TestFkModels.cs" />
    <Compile Remove="TestData\User.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="TestData\TestCase1\Order.cs" />
    <None Include="TestData\TestCase1\Profile.cs" />
    <None Include="TestData\TestCase1\User.cs" />
    <None Include="TestData\TestFkCases\TestFkModels.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.assert" Version="2.9.3" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
	  
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EFfluentify.Application\EFfluentify.Application.csproj" />
    <ProjectReference Include="..\EFfluentify.Infrastructure\EFfluentify.Infrastructure.csproj" />
  </ItemGroup>
</Project>
