// <auto-generated />
namespace EFFluentify.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

internal sealed class InvoiceConfiguration : IEntityTypeConfiguration<Invoice>
{
    public void Configure(EntityTypeBuilder<Invoice> builder)
    {
        builder.ToTable("Invoices");
        builder.HasKey(e => e.Id);
        builder.Property(x => x.Id).ValueGeneratedOnAdd();
        builder.Property(x => x.Number).HasColumnType("char(10)").HasComment("Human-readable invoice number");
        builder.Property(x => x.Amount).HasPrecision(12, 2).HasDefaultValue(0);
        builder.Property(x => x.IsPaid).HasDefaultValue(false);
        builder.Property(x => x.CreatedUtc).ValueGeneratedOnAddOrUpdate();
        builder.Property(x => x.PublicId).ValueGeneratedNever();
        builder.Property(x => x.Notes).IsRequired(false);
    }
}

internal sealed class ExchangeRateConfiguration : IEntityTypeConfiguration<ExchangeRate>
{
    public void Configure(EntityTypeBuilder<ExchangeRate> builder)
    {
        builder.HasIndex(e => new { e.Currency, e.Year }).IsUnique().HasDatabaseName("IX_ExchangeRate_Currency_Year");
        builder.HasKey(e => new { e.Currency, e.Year });
        builder.Property(x => x.Rate).HasPrecision(18, 6);
    }
}